### ISSUE TITLE
Opensource

### ISSUE THREAD

**Issue by WeirdODKnight** [ayush-lab/Coursera-Clone#1]
Can you upload a video on how to run the app?
Thanks!

By the way, good work!

**Comment by ayush-lab** [comment]
Sure! will do so in a few days. A bit tight on schedule here. Thanks btw

**Comment by ayush-lab** [comment]
@WeirdODKnight My apologies for not being able to upload the video, please follow the readme instructions to set it up and yet if there is some problem, then feel free to ask.

**Comment by WeirdODKnight** [comment]
Ok, Thanks.
I don't know anything about Redis that is why.
But Thank you for your work and Reply.
I will figure it out.
Regards.

**Comment by Shubham29012001** [comment]
Hey Ayush,

It would be great if you could create a video demonstrating the process of how to run the complete project? Your project is outstanding!!!

Regards,
Shubham Maurya

**Comment by ayush-lab** [comment]
okay Shubham, I will do that soon and thanks a lot!

**Comment by usamamahmood01** [comment]
waiting for the video....

**Comment by usamamahmood01** [comment]
Hello Ayush, I hope you are doing well, is it possible that you can upload the tutorial for running the project and connecting the Db with the app? I understand you might be busy or have a tight schedule just like us, but it would be a great help if would do the tutorial.

Thank you for your time and help,

Regards,
Usama Mahmood.

**Comment by MarcPartensky** [comment]
Hi I'm also trying to deploy the apps and fixed all the connexions so far. But when I'm trying to signup i get the following message :
![2024-01-31_17:44:42](https://github.com/ayush-lab/Coursera-Clone/assets/38857901/e952d156-8f0a-461a-818d-ecaa0fd3cc63)

Here are the logs as well:
 Error: Validation failed
coursera-clone-back-1           |     at exports.signup (/usr/src/app/controllers/auth.js:29:21)
coursera-clone-back-1           |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
coursera-clone-back-1           |     at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
coursera-clone-back-1           |     at middleware (/usr/src/app/node_modules/express-validator/src/middlewares/check.js:16:13) {
coursera-clone-back-1           |   statusCode: 422,
coursera-clone-back-1           |   data: [
coursera-clone-back-1           |     {
coursera-clone-back-1           |       value: 'fake.fake@fake.fake',
coursera-clone-back-1           |       msg: 'Command find requires authentication',
coursera-clone-back-1           |       param: 'email',
coursera-clone-back-1           |       location: 'body'
coursera-clone-back-1           |     }
coursera-clone-back-1           |   ]
coursera-clone-back-1           | } undefined

Apparently I need to be authenticated to signup which doesn't make sense to me. Also I tried running the jest tests and none of them succeeded.
![2024-01-31_17:48:19](https://github.com/ayush-lab/Coursera-Clone/assets/38857901/c307b742-1e8b-4524-8a6b-2d459805cb29)

Is there something I can do to fix this?
